/*
 * This file is part of Mass Control Tycoon.
 * Copyright 2013-2014 by MCT Team (see TEAM file) - All rights reserved.
 * Project page @ https://github.com/mctteam/mct
 * Author(s) Martin Kelm
 *
 * Mass Control Tycoon is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * Mass Control Tycoon is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Mass Control Tycoon. If not, see <http://www.gnu.org/licenses/>.
 */
var MCT=MCT||{};MCT.Util=function(){this.jsons={}};MCT.Util.prototype.constructor=MCT.Util;MCT.Util.prototype.quit=function(a){"undefined"==typeof a&&(a=0);global.setTimeout(function(){require("nw.gui").App.closeAllWindows()},a)};MCT.Util.prototype.loadJSON=function(a){if("undefined"==typeof this.jsons[a]){var b="";try{b=require("fs").readFileSync(a,{encoding:"utf8"}),this.jsons[a]=JSON.parse(b)}catch(c){}}return this.jsons[a]};
MCT.Util.prototype.objectLength=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};MCT.Util.prototype.time=function(a,b){var c=1;"unix"==a&&(c=1E3);0<!b&&(b=0);c=(new Date).getTime()/c;if("formated"!=a)return Math.round(c+b);c=new Date(c);return c.getHours()+":"+c.getMinutes()+":"+c.getSeconds()};MCT.Version=function(){};MCT.Version.prototype.constructor=MCT.Version;
MCT.Version.prototype.getCommitHash=function(a){return require("fs").readFile("./.git/refs/heads/master",{encoding:"utf8"},function(b,c){b||a(c.replace("\n",""))})};
MCT.Version.prototype.getVersionHash=function(a){var b=function(a,d){var f=require("fs"),k=require("crypto"),l=null,n={},p=null;f.readdir(a,function(q,r){if(q)return d(q);var e=0;(function s(){var m=r[e++];if(!m)return d(null,n);m=a+"/"+m;f.stat(m,function(a,c){c&&c.isDirectory()?b(m,function(a,b){for(var c in b)b.hasOwnProperty(c)&&(n[c]=b[c]);s()}):".js"==m.substring(m.length-3)||".json"==m.substring(m.length-5)||".html"==m.substring(m.length-5)?(l=k.createHash("sha1"),p=f.ReadStream(m),p.on("data",
function(a){l.update(a)}),p.on("end",function(){n[m]=l.digest("hex");s()})):s()})})()})};b("./lib",function(b,d){if(b)throw b;var f=require("crypto"),k=Object.keys(d);k.sort();for(var l="",n=0;n<k.length;n++)l+=d[k[n]];a(f.createHash("sha1").update(l).digest("hex"))})};
MCT.Version.prototype.updateHashesFile=function(){var a=require("fs"),b=this;a.readFile("./HASHES",{encoding:"utf8"},function(c,d){if(!c){var f=d.split("\n"),k=0<f.length?f[f.length-1].split(" "):"";b.getVersionHash(function(c){""!==k&&k[0]=="V"+c||b.getCommitHash(function(b){if(""===k||k[1]!="C"+b){var d="V"+c+" C"+b;f.push(d);b="";for(var q=0,r=0;r<f.length;r++)""!==$.trim(f[r])&&(0<q&&(b+="\n"),b+=f[r],q++);a.writeFile("./HASHES",b,function(a){console.log("Updated version info: "+d)})}})})}})};
MCT.Game=function(){this.elements={}};MCT.Game.prototype.constructor=MCT.Game;
MCT.Game.prototype.start=function(){mct.audioHandler.setPlayers();mct.audioHandler.nextPlaylistTrack();this.elements.planets={anuka:new MCT.Planet("anuka",1,1)};var a={dynEventTitle:"lt.dynEventTitle",dynEventDescription:"lt.dynEventDescription",dynEventWinMessage:"lt.dynEventWinMessage",dynEventFailMessage:"lt.dynEventFailMessage"};this.elements.panels={windowPlanetCompanies:new MCT.DisplayUIPanelWindow("wplanetcompanies",{dynTexts:{dynPlanetTitle:this.elements.planets.anuka.name}},"planet/companies"),
windowSpaceMsg:new MCT.DisplayUIPanelWindow("wspacemsg",{dynTexts:a},"event/message")};this.elements.space=new MCT.Space(1,1,this.elements.planets);mct.sceneHandler.addScene("space",{space:this.elements.space,window:this.elements.panels.windowPlanetCompanies,windowSpaceMsg:this.elements.panels.windowSpaceMsg});this.elements.panels.menu=new MCT.DisplayUIPanelMenu;this.elements.panels.windowWelcomeMsg=new MCT.DisplayUIPanelWindow("wwelcomemsg",{dynTexts:a},"event/message");mct.sceneHandler.addScene("menu",
{menu:this.elements.panels.menu,window:this.elements.panels.windowWelcomeMsg});mct.sceneHandler.showScene("space")};MCT.Element=function(a,b){this.name=a||(b||"random")+Math.floor(1E3*Math.random());this.layout=this.grid=null;PIXI.EventTarget.call(this)};MCT.Element.prototype.constructor=MCT.Element;MCT.Grid=function(a){if(!(0<=a.width&&0<=a.height))throw Error("MCT.Grid, broken size dependency.");this.size={width:Math.floor(a.width),height:Math.floor(a.height)};this.nodes=[]};
MCT.Grid.prototype.constructor=MCT.Grid;MCT.Grid.prototype.checkNode=function(a,b){if(a.x>this.size.width)throw Error("MCT.Grid, node.x out of range.");if(a.y>this.size.height)throw Error("MCT.Grid, node.y out of range.");"undefined"!=typeof b&&b(a);for(var c=0;c<this.nodes.length;c++)if(this.nodes[c].x==a.x&&this.nodes[c].y==a.y)return c;return-1};
MCT.Grid.prototype.addNode=function(a,b){var c=this.checkNode(a);return-1==c?(this.nodes.push(a),this.nodes[this.nodes.length-1]):-1<c?this.nodes[c]:!0===b?-1:null};MCT.Grid.prototype.addNodes=function(a,b,c){for(var d=null,f=[],k=a.x;k<=b.x;k++)for(var l=a.y;l<=b.y;l++)d=this.addNode({x:k,y:l},c),null!==d&&f.push(d);return f};
MCT.Layout=function(a,b){if(!1===a instanceof MCT.Grid)throw Error("MCT.Layout, broken grid dependency.");this.grid=a;this.parts={};b.center=!0===b.center&&"object"==typeof b.size?{x:Math.floor(this.grid.size.width/2)*(b.size.width/this.grid.size.width),y:Math.floor(this.grid.size.height/2)*(b.size.height/this.grid.size.height)}:!1;this.displayObjects=new MCT.DisplayObjects(b);"object"==typeof b.position&&this.displayObjects.move(b.position,!0)};MCT.Layout.prototype.constructor=MCT.Layout;
MCT.Layout.prototype.addPart=function(a){a.anchor=!0===a.anchor?!0:!1;"undefined"!=typeof a.name&&!0===this.parts[a.name].anchor&&(a.anchor=!0);if(0<=a.x&&0<=a.y){a.x=Math.floor(a.x);a.y=Math.floor(a.y);var b=[];(!1==a.anchor||"undefined"!=this.parts[a.name]&&!0===a.anchor)&&0<a.width&&0<a.height?(a.width=Math.floor(a.width),a.height=Math.floor(a.height),b=this.grid.addNodes({x:a.x,y:a.y},{x:a.x+a.width-1,y:a.y+a.height-1})):(b=this.grid.addNodes({x:a.x,y:a.y},{x:a.x,y:a.y}),!1===a.anchor&&(a.width=
1,a.height=1));if(0<b.length){if("undefined"==typeof a.name){var c="part"+mct.util.objectLength(this.parts);"undefined"!=typeof a.namePrefix&&(c=a.namePrefix+c);this.parts[c]={x:a.x,y:a.y,width:a.width,height:a.height,anchor:a.anchor,zindex:a.zindex||1,nodes:b,displayObject:!1}}else for(var d=0;d<b.length;d++)-1==this.parts[a.name].nodes.indexOf(b[d])&&this.parts[a.name].nodes.push(b[d]);return c}return null}throw Error("MCT.Layout, broken part position dependency.");};
MCT.Layout.prototype.addPartOptions=function(a,b){this.parts[a]=$.extend(this.parts[a],b)};MCT.Layout.prototype.addDisplayObjectToPart=function(a,b,c,d){"undefined"!=typeof this.parts[a]&&(this.parts[a].displayObject=this.displayObjects.add(b,c,d),this.parts[a].displayObject instanceof MCT.DisplayObject&&this.setDisplayObjectPositionByPart(a))};
MCT.Layout.prototype.setDisplayObjectPositionByPart=function(a){var b="string"==typeof a?this.parts[a]:a;delete a;"undefined"!=typeof b&&(a=this.displayObjects.getScale(),b.displayObject.setPosition({x:b.x*this.displayObjects.size.width/this.grid.size.width*a.x,y:b.y*this.displayObjects.size.height/this.grid.size.height*a.y}))};
MCT.Layout.prototype.setDisplayObjectSizeByPart=function(a){var b="string"==typeof a?this.parts[a]:a;delete a;"undefined"!=typeof b&&(a=this.displayObjects.getScale(),b.displayObject.setSize({width:b.width*this.displayObjects.size.width/this.grid.size.width*a.x,height:b.height*this.displayObjects.size.height/this.grid.size.height*a.y}))};MCT.Layout.prototype.getPart=function(a){return"undefined"!=typeof this.parts[a]?this.parts[a]:null};
MCT.Layout.prototype.setVisibility=function(a){if(!1===a)this.displayObjects.setVisibility(a);else{for(var b in this.parts)!1!==this.parts[b].visible&&this.parts[b].displayObject instanceof MCT.DisplayObject&&this.parts[b].displayObject.setVisibility(a);this.displayObjects.setVisibility(a,!0)}};
MCT.Layout.prototype.addHelperNodes=function(a){var b={x:0,y:0,width:this.grid.size.width,height:this.grid.size.height},b=this.addPart(b);"undefined"!=typeof a&&this.addDisplayObjectToPart(b,b,"image",{image:a.image,scale:a.scale});for(a=0;a<this.grid.nodes.length;a++)b={x:this.grid.nodes[a].x,y:this.grid.nodes[a].y,anchor:!0},b=this.addPart(b),this.addDisplayObjectToPart(b,b+a,"graphic",{fillColor:"FFFFFF",width:5,height:5,center:!0})};
MCT.Space=function(a,b,c){MCT.Element.call(this,!1,"space");this.planets=c||{};b=25*b||1;this.grid=new MCT.Grid({width:b,height:b});b={width:1E3*a||1,height:1E3*a||1};this.layout=new MCT.Layout(this.grid,{elementHandle:"space",size:b,center:!0,zoom:!0,zoomX:25,zoomY:25});c={x:0,y:0,anchor:!0};c=this.layout.addPart(c);this.layout.addDisplayObjectToPart(c,"spaceBgStars","image",{image:"data/display/gfx/splitted/ti_stars.png",tiling:!0,width:b.width,height:b.height,tileScale:{x:0.03,y:0.03}});this.layout.addDisplayObjectToPart(c,
"spaceBgInteractionLayer","image",{image:"blank",interaction:{type:"mousedown",element:this,content:{action:"moveSpace"}},width:b.width,height:b.height});this.addEventListener("mousedown",this.onMouseDown.curry());this.layout.addHelperNodes({scale:{x:a,y:a}});c={x:this.grid.size.width/2,y:this.grid.size.height/2,anchor:!0};c=this.layout.addPart(c);this.planets.anuka.layout.displayObjects.container.scale={x:0.03,y:0.03};this.layout.addDisplayObjectToPart(c,"planetAnuka","container",{owner:this.planets.anuka.layout.displayObjects})};
MCT.Space.prototype=Object.create(MCT.Element.prototype);MCT.Space.prototype.constructor=MCT.Space;
MCT.Space.prototype.onMouseDown=function(a){var b=a.content;"moveSpace"==b.action&&(b.element.mouseMoveCoor={x:0,y:0},b.mouse.target.mousemove=function(){b.element.dispatchEvent({type:"mousemove",content:b})},b.element.addEventListener("mousemove",b.element.onMouseMove.curry()),b.mouse.target.mouseup=function(){b.element.dispatchEvent({type:"mouseup",content:b})},b.element.addEventListener("mouseup",b.element.onMouseUp.curry()))};
MCT.Space.prototype.onMouseMove=function(a){"moveSpace"==a.content.action&&(a=a.content,0<a.element.mouseMoveCoor.x&&0<a.element.mouseMoveCoor.y&&a.element.layout.displayObjects.move({x:a.mouse.originalEvent.screenX-a.element.mouseMoveCoor.x,y:a.mouse.originalEvent.screenY-a.element.mouseMoveCoor.y}),a.element.mouseMoveCoor={x:a.mouse.originalEvent.screenX,y:a.mouse.originalEvent.screenY})};
MCT.Space.prototype.onMouseUp=function(a){a=a.content;"moveSpace"==a.action&&(a.mouse.target.mousemove=null,a.element.removeEventListener("mousemove",a.element.onMouseMove.curry()),a.mouse.target.mouseup=null,a.element.removeEventListener("mouseup",a.element.onMouseUp.curry()))};
MCT.Planet=function(a,b,c){MCT.Element.call(this,a);a=25*c||1;this.grid=new MCT.PlanetGrid({width:a,height:a});this.layout=new MCT.PlanetLayout(this.grid,{elementHandle:"planet",size:{width:1E3*b||1,height:1E3*b||1},center:!0});this.layout.addHelperNodes({image:"mct_planet_anuka",scale:{x:b,y:b}});this.layout.addBuilding({name:"investmentsCenter",image:"investments_center",x:Math.floor(0.5*a),y:Math.floor(0.5*a),scale:{x:b,y:b},interaction:{type:"click",element:this,content:{action:"openInvestmentCenter"}}});
this.addEventListener("click",this.onMouseClick.curry())};MCT.Planet.prototype=Object.create(MCT.Element.prototype);MCT.Planet.prototype.constructor=MCT.Planet;MCT.Planet.prototype.onMouseClick=function(a){"openInvestmentCenter"==a.content.action&&mct.audioHandler.playEffect("ef.click1")};MCT.PlanetGrid=function(a){MCT.Grid.call(this,a);this.radius=this.size.width/2};MCT.PlanetGrid.prototype=Object.create(MCT.Grid.prototype);MCT.PlanetGrid.prototype.constructor=MCT.PlanetGrid;
MCT.PlanetGrid.prototype.checkNode=function(a){"undefined"!=typeof this.nodes[Number(a)]&&(a=this.nodes[Number(a)]);try{return MCT.Grid.prototype.checkNode.call(this,{x:a.x,y:a.y,gridRadius:this.radius},function(a){if(!1===Math.sqrt(Math.pow(a.x-a.gridRadius,2)+Math.pow(a.y-a.gridRadius,2))<a.gridRadius)throw Error("MCT.PlanetGrid, node.position out of range.");})}catch(b){return-2}};MCT.PlanetLayout=function(a,b){MCT.Layout.call(this,a,b)};MCT.PlanetLayout.prototype=Object.create(MCT.Layout.prototype);
MCT.PlanetLayout.prototype.constructor=MCT.PlanetLayout;
MCT.PlanetLayout.prototype.addBuilding=function(a){var b=this.addPart({anchor:!0,namePrefix:"building_",x:a.x,y:a.y});if(null===b)throw Error("MCT.PlanetLayout, building is out of range.");if("undefined"==typeof a.name)throw Error("MCT.PlanetLayout, broken building name dependency.");if("undefined"==typeof a.image)throw Error("MCT.PlanetLayout, broken building image dependency.");this.addDisplayObjectToPart(b,a.name,"button",{image:"building_"+a.image,scale:a.scale,interaction:a.interaction});return this.parts[b]};
MCT.PlanetLayout.prototype.addArea=function(a){var b=this.addPart({namePrefix:"area_",x:a.x,y:a.y,width:a.width,height:a.height});if(null===b)throw Error("MCT.PlanetLayout, area is out of range.");"undefined"!=typeof a.image?this.addDisplayObjectToPart(b,b,"image",{image:a.image,scale:a.scale}):this.addDisplayObjectToPart(b,b,"graphic",{fillColor:"FFFFFF",width:5,height:5});return this.parts[b]};
MCT.PlanetLayout.prototype.getPart=function(a,b){var c="";switch(a){case "building":c="building_"+b;break;case "area":c="area_"+b}MCT.Layout.prototype.getPart.call(this,c)};MCT.Player=function(a,b){this.name=a||"random"+Math.floor(1E3*Math.random());this.type=b||"human"};MCT.Player.prototype.constructor=MCT.Player;MCT.Player.prototype.turn=function(){console.log(this.type+" player "+this.name+" makes a turn")};MCT.PlayerCpu=function(a){MCT.Player.call(this,a,"cpu")};MCT.PlayerCpu.prototype=Object.create(MCT.Player.prototype);
MCT.PlayerCpu.prototype.constructor=MCT.PlayerCpu;MCT.DisplayObject=function(a,b,c){this.type=a||null;this.options=b||null;this.container=c||null};MCT.DisplayObject.prototype.constructor=MCT.DisplayObject;MCT.DisplayObject.prototype.current=function(){if(null===container){if(null===type)throw Error("MCT.DisplayObject, broken type dependency.");if(null===options)throw Error("MCT.DisplayObject, broken options dependency.");this.create()}if(null!==this.container)return this.container};
MCT.DisplayObject.prototype.setPosition=function(a){this.container.position.x=a.x;this.container.position.y=a.y};MCT.DisplayObject.prototype.createContainer=function(a,b){this.container=new PIXI.DisplayObjectContainer;!0===a&&"object"==typeof b&&(this.container.pivot.x=b.width/2,this.container.pivot.y=b.height/2);return this.container};
MCT.DisplayObject.prototype.create=function(){switch(this.type){case "text":var a=this.getText(this.options);if(a instanceof PIXI.Text)this.createContainer().addChild(a);else return!1;break;case "image":this.createImage(this.options);break;case "graphic":this.createGraphic(this.options);break;case "button":this.createButton(this.options)}return!0};
MCT.DisplayObject.prototype.createImage=function(a){var b=this.createContainer();a.images="object"!=typeof a.image?[a.image]:a.image;"undefined"!=typeof a.alpha&&"object"!=typeof a.alpha?a.alphas=[a.alpha]:"undefined"!=typeof a.alpha&&(a.alphas=a.alpha);for(var c=0;c<a.images.length;c++)a.image=a.images[c],"undefined"!=typeof a.alphas&&("undefined"!=typeof a.alphas[c]?a.alpha=a.alphas[c]:delete a.alpha),b.addChild(this.getSprite(a))};
MCT.DisplayObject.prototype.getSprite=function(a){var b=PIXI.Texture.fromFrame(a.image||"blank");!0===a.tiling?(b=new PIXI.TilingSprite(b),"undefined"!=typeof a.tileScale&&(b.tileScale=a.tileScale)):b=new PIXI.Sprite(b);b.width="undefined"==typeof a.width?b.texture.width:a.width;b.height="undefined"==typeof a.height?b.texture.height:a.height;"undefined"!=typeof a.scale&&(0<a.scale.x&&(b.scale.x=a.scale.x),0<a.scale.y&&(b.scale.y=a.scale.y));"object"==typeof a.anchor&&(0<a.anchor.x&&(b.anchor.x=a.anchor.x),
0<a.anchor.y&&(b.anchor.y=a.anchor.y));"undefined"!=typeof a.alpha&&(b.alpha=a.alpha);b.position.x=0;b.position.y=0;"undefined"!=typeof a.interaction&&this.setInteraction(b,a.interaction);return b};
MCT.DisplayObject.prototype.getText=function(a){var b=100;"undefined"!=typeof a.style?(style={font:a.style[0]+"px "+a.style[1],fill:a.style[2]},b=Number(a.style[3])):style=null;if("object"==typeof a.value&&0<a.value.length){for(var c="",d=0;d<a.value.length;d++)0<d&&(c+=" "),c+=a.value[d];a.value=c;delete c}if(a.value.length>b){var c="",d=-1,f=0,k=[];do if(d++,d<a.value.length&&(0<c.length||" "!=a.value.substring(d,d+1))&&(c+=a.value.substring(d,d+1),c.length==b)){var f=0,l=a.value.substring(d+1,
d+2);if(""!==c.substring(c.length-1)&&" "!=l){f=c.length-1;do f--;while(" "!=c.substring(f,f+1))}0<f?(k.push(c.substring(0,f+1)),c=c.substring(f+1)):(k.push(c),c="")}while(d<a.value.length-1);""!==c&&k.push(c);if(0<k.length)for(a.value="",d=0;d<k.length;d++)0<d&&(a.value+="\n"),a.value+=k[d]}if("lt."===a.value.substring(0,3))return!1;b=new PIXI.Text(a.value,style);b.anchor.x=0.5;b.anchor.y=0.5;"undefined"!=typeof a.anchor&&("undefined"!=typeof a.anchor.x&&(b.anchor.x=a.anchor.x),"undefined"!=typeof a.anchor.y&&
(b.anchor.y=a.anchor.y));"undefined"!=typeof a.position&&("undefined"!=a.position.x&&(b.position.x=a.position.x),"undefined"!=a.position.y&&(b.position.y=a.position.y));return b};MCT.DisplayObject.prototype.createGraphic=function(a){var b=new PIXI.Graphics;b.position.x=0;b.position.y=0;b.beginFill("0x"+a.fillColor);"undefined"!=typeof a.border&&b.lineStyle(a.border.size,"0x"+a.border.color);b.drawRect(0,0,a.width,a.height);this.createContainer(a.center,{width:a.width,height:a.height}).addChild(b)};
MCT.DisplayObject.prototype.createButton=function(a){var b=this.createContainer();if("undefined"!=typeof a.text)var c=this.getText(a.text);var d=this.getSprite(a);if("undefined"!=typeof c){if("undefined"!=typeof a.text.borderSize&&"undefined"!=typeof a.text.borderSize.vertical){var f=a.text.borderSize.vertical*a.text.style[0];d.width=c.width+f+f}else d.width=c.width;"undefined"!=typeof a.text.borderSize&&"undefined"!=typeof a.text.borderSize.horizontal?(f=a.text.borderSize.horizontal*a.text.style[0],
d.height=c.height+f+f):d.height=c.height}b.addChild(d);"undefined"!=typeof c&&(c.position.x=d.width/2,c.position.y=d.height/2,"object"==typeof a.anchor&&(0<a.anchor.x&&(c.anchor.x=a.anchor.x,c.position.x=0),0<a.anchor.y&&(c.anchor.y=a.anchor.y,c.position.y=0)),b.addChild(c))};
MCT.DisplayObject.prototype.setInteraction=function(a,b){if(b.element instanceof MCT.Element&&"undefined"!=typeof b.type){a.setInteractive(!0);var c={element:b.element};$.extend(c,b.content);var d=function(a){$.extend(c,{mouse:a});b.element.dispatchEvent({type:b.type,content:c})};switch(b.type){case "click":a.click=d;break;case "mousedown":a.mousedown=d}}};
MCT.DisplayObject.prototype.setVisibility=function(a){this.container.visible=a;for(var b=0;b<this.container.children.length;b++)this.container.children[b].visibility=a};MCT.DisplayObject.prototype.getVisibility=function(){return this.container.visible};
MCT.DisplayObject.prototype.getSize=function(){var a=0,b=0;"undefined"!=typeof this.container.children[0]&&("number"==typeof this.container.children[0].width&&"number"==typeof this.container.children[0].height)&&(a=this.container.children[0].width,b=this.container.children[0].height);return{width:a,height:b}};
MCT.DisplayObject.prototype.setSize=function(a){"undefined"!=typeof this.container.children[0]&&("number"==typeof a.width&&"number"==typeof a.height)&&("graphic"==this.type?(this.container.children[0].scale={x:a.width,y:a.height},this.container.pivot={x:a.width/2,y:a.height/2}):"image"==this.type&&(this.container.children[0].width=a.width,this.container.children[0].height=a.height))};
MCT.DisplayObjects=function(a){if("undefined"==typeof mct.userConfig)throw Error("MCT.DisplayObjects, broken user config dependency.");this.list={};this.texturesOptions={};this.textStylesOptions={};this.textTranslations={};"undefined"!=typeof a.elementHandle&&(this.loadTexturesOptions(a.elementHandle),this.loadTextStylesOptions(a.elementHandle),this.loadTextTranslations(a.elementHandle));this.size=null;"undefined"!=typeof a.size&&(this.size=a.size);this.center=a.center||!1;this.container=this.createContainer();
this.baseScale={x:0,y:0};this.zoomScale={x:[a.zoomX||0,1.1],y:[a.zoomY||0,1.1]};!0===a.zoom&&this.activateZoom()};MCT.DisplayObjects.prototype.constructor=MCT.DisplayObjects;
MCT.DisplayObjects.prototype.createContainer=function(){this.container=new PIXI.DisplayObjectContainer;!1!==this.center&&"object"==typeof this.center?(this.container.pivot={x:this.center.x,y:this.center.y},this.container.position={x:mct.pixi.screen.width/2,y:mct.pixi.screen.height/2}):(this.container.position.x=0,this.container.position.y=0);this.container.visible=!1;return this.container};
MCT.DisplayObjects.prototype.activateZoom=function(){var a=this;$("html").bind("mousewheel",function(b){0<b.originalEvent.wheelDelta/120?(a.zoomScale.x[0]++,a.zoomScale.y[0]++):(a.zoomScale.x[0]--,a.zoomScale.y[0]--);a.setScale()})};
MCT.DisplayObjects.prototype.setScale=function(a){"undefined"!=typeof a&&(this.baseScale=a);"undefined"!=typeof this.zoomScale&&(this.container.scale.x=0<this.zoomScale.x[0]?this.baseScale.x*Math.pow(this.zoomScale.x[1],this.zoomScale.x[0]):0>this.zoomScale.x[0]?this.baseScale.x/Math.pow(this.zoomScale.x[1],Math.abs(this.zoomScale.x[0])):this.baseScale.x,this.container.scale.y=0<this.zoomScale.y[0]?this.baseScale.y*Math.pow(this.zoomScale.y[1],this.zoomScale.y[0]):0>this.zoomScale.y[0]?this.baseScale.y/
Math.pow(this.zoomScale.y[1],Math.abs(this.zoomScale.y[0])):this.baseScale.y)};MCT.DisplayObjects.prototype.getScale=function(){return this.container.scale};
MCT.DisplayObjects.prototype.loadTextStylesOptions=function(a){try{if(this.textStylesOptions=mct.util.loadJSON("./lib/data/display/txt/elements/"+a+"/styles.json"),"object"==typeof this.textStylesOptions.externals&&0<this.textStylesOptions.externals.length){for(a=0;a<this.textStylesOptions.externals.length;a++){var b=mct.util.loadJSON("./lib/data/display/txt/externals/"+this.textStylesOptions.externals[a]+"/styles.json"),c;for(c in b)this.textStylesOptions[c]=b[c]}delete this.textStylesOptions.externals}}catch(d){this.textStylesOptions=
{}}};MCT.DisplayObjects.prototype.loadTextStyleOptions=function(a){a="undefined"!=typeof a.text?a.text:a;"undefined"!=typeof a.style&&"undefined"!=typeof this.textStylesOptions[a.style]&&(a.style=this.textStylesOptions[a.style])};
MCT.DisplayObjects.prototype.loadTextTranslations=function(a){try{if(this.textTranslations=mct.util.loadJSON("./lib/data/display/txt/elements/"+a+"/lngs/"+mct.userConfig.language+".json"),"object"==typeof this.textTranslations.externals&&0<this.textTranslations.externals.length){for(a=0;a<this.textTranslations.externals.length;a++){var b=mct.util.loadJSON("./lib/data/display/txt/externals/"+this.textTranslations.externals[a]+"/lngs/"+mct.userConfig.language+".json"),c;for(c in b)this.textTranslations[c]=
b[c]}delete this.textTranslations.externals}}catch(d){this.textTranslations={}}};MCT.DisplayObjects.prototype.loadTextTranslation=function(a){a="undefined"!=typeof a.text?a.text:a;if("undefined"!=typeof a.value)if("string"==typeof a.value)a.value=this.textTranslations[a.value]||a.value;else if("object"==typeof a.value&&0<a.value.length)for(var b=0;b<a.value.length;b++)a.value[b]=this.textTranslations[a.value[b]]||a.value[b]};
MCT.DisplayObjects.prototype.loadTexturesOptions=function(a){try{this.texturesOptions=mct.util.loadJSON("./lib/data/display/gfx/elements/"+a+"/options.json").textures}catch(b){this.texturesOptions={}}};
MCT.DisplayObjects.prototype.loadTextureOptions=function(a){var b="object"==typeof a.image&&0<a.image.length?a.image[0]:a.image;"string"==typeof b&&"undefined"!=typeof this.texturesOptions[b]&&("undefined"!=typeof this.texturesOptions[b].scale&&("undefined"==typeof a.scale&&(a.scale={x:1,y:1}),a.scale.x*=this.texturesOptions[b].scale.x,a.scale.y*=this.texturesOptions[b].scale.y),"undefined"!=typeof this.texturesOptions[b].anchor&&(a.anchor=this.texturesOptions[b].anchor))};
MCT.DisplayObjects.prototype.add=function(a,b,c){if("container"!=b)if(this.loadTextureOptions(c),this.loadTextStyleOptions(c),this.loadTextTranslation(c),b=new MCT.DisplayObject(b,c),!0===b.create())this.list[a]=b;else return!1;else this.list[a]=new MCT.DisplayObject("container",null,c.owner.container);"undefined"!=typeof this.list[a]&&!0!==c.reference&&this.container.addChild(this.list[a].container);return this.get(a)};
MCT.DisplayObjects.prototype.get=function(a){if("undefined"==typeof this.list[a])throw Error("MCT.DisplayObjects, broken object name dependency.");return this.list[a]};MCT.DisplayObjects.prototype.remove=function(a){"string"==typeof a?(this.container.removeChild(this.list[a]),delete this.list[a]):a instanceof MCT.DisplayObject&&(this.container.removeChild(a),delete a);throw Error("MCT.DisplayObjects, broken object reference dependency to remove object.");};
MCT.DisplayObjects.prototype.setVisibility=function(a,b){this.container.visible=a;if(!0!==b)for(var c in this.list)this.list[c].setVisibility(a)};MCT.DisplayObjects.prototype.getVisibility=function(){return this.container.visible};MCT.DisplayObjects.prototype.move=function(a,b){!0===b?(this.container.position.x=a.x,this.container.position.y=a.y):(this.container.position.x+=a.x,this.container.position.y+=a.y)};
MCT.DisplayScene=function(){if("undefined"==typeof mct.pixi)throw Error("MCT.DisplayScene, broken pixi dependency.");this.layouts=[]};MCT.DisplayScene.prototype.constructor=MCT.DisplayScene;
MCT.DisplayScene.prototype.update=function(a){for(var b=0;b<this.layouts.length;b++){var c=a;"string"==typeof c&&"toggle"==c?(c=!this.layouts[b].displayObjects.getVisibility(),this.layouts[b].setVisibility(c)):"boolean"==typeof c?this.layouts[b].setVisibility(c):c=this.layouts[b].displayObjects.getVisibility();!0===c?-1==mct.pixi.stage.children.indexOf(this.layouts[b].displayObjects.container)?mct.pixi.stage.addChild(this.layouts[b].displayObjects.container):this.layouts[b].displayObjects.setScale({x:mct.pixi.screen.ratio,
y:mct.pixi.screen.ratio}):-1<mct.pixi.stage.children.indexOf(this.layouts[b].displayObjects.container)&&mct.pixi.stage.removeChild(this.layouts[b].displayObjects.container)}};MCT.DisplayScene.prototype.addLayout=function(a){a.displayObjects.setScale({x:mct.pixi.screen.ratio,y:mct.pixi.screen.ratio});this.layouts.push(a)};MCT.DisplaySceneHandler=function(a){this.scenes={};this.lastScene=""};MCT.DisplaySceneHandler.prototype.constructor=MCT.DisplaySceneHandler;
MCT.DisplaySceneHandler.prototype.showScene=function(a){""!=this.lastScene&&this.scenes[this.lastScene].update(!1);this.scenes[a].update(!0);this.lastScene=a};
MCT.DisplaySceneHandler.prototype.addScene=function(a,b){this.scenes[a]=new MCT.DisplayScene;if(b instanceof MCT.Element)this.scenes[a].addLayout(b.layout);else for(var c in b)if(b[c]instanceof MCT.Element)b[c].layout instanceof MCT.Layout&&this.scenes[a].addLayout(b[c].layout);else for(var d in b[c])this.scenes[a].addLayout(b[c][d].layout);this.scenes[a].update()};MCT.DisplaySceneHandler.prototype.update=function(){for(var a in this.scenes)this.scenes[a].update()};
MCT.DisplayUILayout=function(a,b){MCT.Layout.call(this,a,b);this.frames=[]};MCT.DisplayUILayout.prototype=Object.create(MCT.Layout.prototype);MCT.DisplayUILayout.prototype.constructor=MCT.DisplayUILayout;MCT.DisplayUILayout.prototype.addDisplayObjectToPart=function(a,b,c,d){"number"==typeof this.parts[a].frameId&&"object"==typeof this.frames[this.parts[a].frameId]&&(d.reference=!0);MCT.Layout.prototype.addDisplayObjectToPart.call(this,a,b,c,d);!1!==this.parts[a].displayObject&&!0===d.reference&&this.frames[this.parts[a].frameId].displayObject.container.addChild(this.parts[a].displayObject.container)};
MCT.DisplayUILayout.prototype.addFrame=function(a){"object"!=typeof a&&(a={});var b=this.addPart({anchor:!0,namePrefix:"frame_",x:a.x||0,y:a.y||0,width:a.width||1,height:a.height||1,zindex:0});this.addPartOptions(b,{visible:a.visible||!0,padding:a.padding||{}});this.addDisplayObjectToPart(b,b,"graphic",{fillColor:a.color||"424242",width:a.width||1,height:a.height||1});this.frames.push(this.parts[b]);return this.frames.length-1};
MCT.DisplayUILayout.prototype.calculate=function(a){var b=[],c;for(c in this.parts)!0===this.parts[c].visible&&this.parts[c].frameId==a&&("undefined"==typeof b[this.parts[c].zindex-1]&&(b[this.parts[c].zindex-1]={top:{parts:[]},bottom:{parts:[]}}),"bottom"==this.parts[c].location?b[this.parts[c].zindex-1].bottom.parts.push(this.parts[c]):b[this.parts[c].zindex-1].top.parts.push(this.parts[c]));for(var d=this.displayObjects.size.width/this.grid.size.width,f=this.displayObjects.size.height/this.grid.size.height,
k=c=0,l=null,n,p,q,r,e=0;e<b.length;e++){framePadding=0==e?this.frames[a].padding||{}:{};b[e].maxWidth=0;b[e].spaces={top:0+(framePadding.top||0),bottom:0};for(var g in b[e].spaces){if("bottom"==g){b[e].spaces.bottom=b[e].spaces.top;var s=b[e].bottom.parts.length-1,m=-1,u=0}else var s=0,m=1,v=b[e].top.parts.length-1;if(0<b[e][g].parts.length){var t=0;do{var h=t*m+s;b[e][g].parts[h].displayObject instanceof MCT.DisplayObject&&("object"==typeof b[e][g].parts[h].padding?(n="undefined"!=typeof b[e][g].parts[h].padding.left?
(framePadding.left||0)+Number(b[e][g].parts[h].padding.left):framePadding.left||0,p="undefined"!=typeof b[e][g].parts[h].padding.right?Number(b[e][g].parts[h].padding.right):0,q="undefined"!=typeof b[e][g].parts[h].padding.top?Number(b[e][g].parts[h].padding.top):0,r="undefined"!=typeof b[e][g].parts[h].padding.bottom?Number(b[e][g].parts[h].padding.bottom):0):n=framePadding.left||0,l=b[e][g].parts[h].displayObject.getSize(),b[e][g].parts[h].width=Math.ceil(l.width/d),b[e][g].parts[h].height=Math.ceil(l.height/
f),b[e][g].parts[h].x=n||0,b[e][g].parts[h].y=b[e].spaces[g]+(q||0),this.setDisplayObjectPositionByPart(b[e][g].parts[h]),c<b[e][g].parts[h].width+(n||0)+(p||0)&&(c=b[e][g].parts[h].width+(n||0)+(p||0)),b[e].maxWidth<b[e][g].parts[h].width+(n||0)+(p||0)&&(b[e].maxWidth=b[e][g].parts[h].width+(n||0)+(p||0)),b[e].spaces[g]+=(r||0)+(q||0)+b[e][g].parts[h].height);t++}while("bottom"==g&&h>u||"top"==g&&h<v)}}c+=framePadding.right||0;k+=b[e].spaces.bottom+(framePadding.bottom||0);for(g in b[e].spaces)for(h=
0;h<b[e][g].parts.length;h++)"left"!=b[e][g].parts[h].align&&b[e][g].parts[h].displayObject instanceof MCT.DisplayObject&&("right"==b[e][g].parts[h].align?(b[e][g].parts[h].x=b[e].maxWidth-b[e][g].parts[h].width,this.setDisplayObjectPositionByPart(b[e][g].parts[h])):"center"==b[e][g].parts[h].align&&(b[e][g].parts[h].x=Math.floor(c/2-b[e][g].parts[h].width/2),this.setDisplayObjectPositionByPart(b[e][g].parts[h])))}a=this.frames[a];a.x=Math.floor(this.grid.size.width/2);a.y=Math.floor(this.grid.size.height/
2);this.setDisplayObjectPositionByPart(a);a.width=c;a.height=k;this.setDisplayObjectSizeByPart(a)};MCT.DisplayUIPanel=function(a,b,c){MCT.Element.call(this,a,"panel");this.grid=new MCT.Grid({width:1280/(b||1),height:1024/(b||1)});this.layout=new MCT.DisplayUILayout(this.grid,{elementHandle:a+"panel",size:{width:1280,height:1024},position:c})};MCT.DisplayUIPanel.prototype=Object.create(MCT.Element.prototype);MCT.DisplayUIPanel.prototype.constructor=MCT.DisplayUIPanel;
MCT.DisplayUIPanelMenu=function(){MCT.DisplayUIPanel.call(this,"menu");var a={x:this.grid.size.width-1,y:this.grid.size.height-1,anchor:!0},a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,"menuBgPlanet1","image",{image:"mct_planet"});a={x:0,y:0,anchor:!0};a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,"menuBgPlanet2","image",{image:"mct_planet"});a={x:this.grid.size.width/2,y:this.grid.size.height/2-0.05*this.grid.size.height,anchor:!0};a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,
"menuLogo","image",{image:"mct_logo"});a={x:this.grid.size.width/2,y:this.grid.size.height/2-0.3*this.grid.size.height,anchor:!0};a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,"menuGameTitle","text",{value:"lt.menuGameTitle",style:"gametitle1"});a={x:this.grid.size.width/2-0.15*this.grid.size.width,y:this.grid.size.height/2+0.2*this.grid.size.height,anchor:!0};a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,"menuButtonStart","button",{image:"mct_menu_button",interaction:{type:"click",
element:this,content:{action:"start"}},text:{value:"lt.menuButtonStart",style:"menubutton1",borderSize:{vertical:1,horizontal:0.3}}});a={x:this.grid.size.width/2+0.15*this.grid.size.width,y:this.grid.size.height/2+0.2*this.grid.size.height,anchor:!0};a=this.layout.addPart(a);this.layout.addDisplayObjectToPart(a,"menuButtonQuit","button",{image:"mct_menu_button",interaction:{type:"click",element:this,content:{action:"quit"}},text:{value:"lt.menuButtonQuit",style:"menubutton1",borderSize:{vertical:1,
horizontal:0.3}}});this.addEventListener("click",this.onButtonClick.curry())};MCT.DisplayUIPanelMenu.prototype=Object.create(MCT.DisplayUIPanel.prototype);MCT.DisplayUIPanelMenu.prototype.constructor=MCT.DisplayUIPanelMenu;MCT.DisplayUIPanelMenu.prototype.onButtonClick=function(a){if("undefined"!=typeof a.content.action)switch(a.content.action){case "start":mct.audioHandler.playEffect("ef.click1");mct.sceneHandler.showScene("space");break;case "quit":mct.audioHandler.playEffect("ef.click1"),mct.util.quit(500)}};
MCT.DisplayUIPanelWindow=function(a,b,c){MCT.DisplayUIPanel.call(this,a||"window"+1E3*Math.random(),b.unitSize,b.position);this.config=mct.util.loadJSON("./lib/data/display/window/"+c+".json");this.dynTexts=b.dynTexts||{};this.frameId=this.layout.addFrame({color:this.config.color,padding:this.config.padding});for(a=0;a<this.config.layers.length;a++)this.initializeLayer(a),this.setTitles(a),this.setMenus(a),this.setContents(a);this.addEventListener("click",this.onButtonClick.curry());this.layout.calculate(this.frameId)};
MCT.DisplayUIPanelWindow.prototype=Object.create(MCT.DisplayUIPanel.prototype);MCT.DisplayUIPanelWindow.prototype.constructor=MCT.DisplayUIPanelWindow;MCT.DisplayUIPanelWindow.prototype.getDynText=function(a){if("string"==typeof a)a=this.dynTexts[a]||a;else if("object"==typeof a&&0<a.length)for(var b=0;b<a.length;b++)a[b]=this.dynTexts[a[b]]||a[b];return a};
MCT.DisplayUIPanelWindow.prototype.initializeLayer=function(a){var b=this.config.layers[a];b.visible=Boolean(b.visible);b.interactions={status:{current:""}};if("object"==typeof b.titles&&0<b.titles.length)for(var c=0;c<b.titles.length;c++)b.titles[c].partName=this.layout.addPart({x:0,y:0,anchor:!0,zindex:a+1}),this.layout.addPartOptions(b.titles[c].partName,{location:"top",align:b.titles[c].align||"left",visible:b.visible,frameId:this.frameId,padding:b.titles[c].padding||{}});if("object"==typeof b.menus&&
0<b.menus.length)for(c=0;c<b.menus.length;c++)b.menus[c].partName=this.layout.addPart({x:0,y:0,anchor:!0,zindex:a+1}),this.layout.addPartOptions(b.menus[c].partName,{location:b.menus[c].location||"top",align:b.menus[c].align||"left",visible:b.visible,frameId:this.frameId,padding:b.menus[c].padding||{}});if("object"==typeof b.contents&&0<b.contents.length)for(c=0;c<b.contents.length;c++)b.contents[c].partName=this.layout.addPart({x:0,y:0,anchor:!0,zindex:a+1}),this.layout.addPartOptions(b.contents[c].partName,
{location:b.contents[c].location||"top",align:b.contents[c].align||"left",visible:b.visible,frameId:this.frameId,padding:b.contents[c].padding||{}})};
MCT.DisplayUIPanelWindow.prototype.setTitles=function(a){var b=this.config.layers[a],c="";if(!0===b.visible&&"object"==typeof b.titles&&0<b.titles.length)for(var d=0;d<b.titles.length;d++)c=b.titles[d].partName,this.layout.parts[c].displayObject instanceof MCT.DisplayObject||this.layout.addDisplayObjectToPart(c,"layer"+a+"title"+d,"text",{style:b.titles[d].textStyle,value:this.getDynText(b.titles[d].text),anchor:{x:0,y:0}})};
MCT.DisplayUIPanelWindow.prototype.setMenus=function(a){var b=this.config.layers[a],c="";if(!0===b.visible&&"object"==typeof b.menus&&0<b.menus.length)for(var d=0;d<b.menus.length;d++)if(c=b.menus[d].partName,!(this.layout.parts[c].displayObject instanceof MCT.DisplayObject)){for(var f=0;f<b.menus[d].buttons.length;f++)"string"==typeof b.menus[d].buttons[f].content&&this.dispatchEvent({type:"menuButtons",content:b.menus[d].buttons[f]});"string"==typeof b.menus[d].buttons[0].text&&this.layout.addDisplayObjectToPart(c,
"layer"+a+"menu"+d+"button0","button",{interaction:{type:"click",element:this,content:{action:b.menus[d].buttons[0].action}},text:{style:b.menus[d].textStyle,value:this.getDynText(b.menus[d].buttons[0].text)},anchor:{x:0,y:0}})}};
MCT.DisplayUIPanelWindow.prototype.setContents=function(a){var b=this.config.layers[a],c="";if(!0===b.visible&&"object"==typeof b.contents&&0<b.contents.length)for(var d=0;d<b.contents.length;d++)c=b.contents[d].partName,this.layout.parts[c].displayObject instanceof MCT.DisplayObject||"undefined"!=typeof b.contents[d].text&&this.layout.addDisplayObjectToPart(c,"layer"+a+"content"+d,"text",{style:b.contents[d].textStyle,value:this.getDynText(b.contents[d].text),anchor:{x:0,y:0}})};
MCT.DisplayUIPanelWindow.prototype.onButtonClick=function(a){if("undefined"!=typeof a.content.action)switch(a.content.action){case "windowClose":mct.audioHandler.playEffect("ef.click1"),a.content.element.layout.setVisibility(!1),mct.sceneHandler.update()}};
MCT.AudioHandler=function(){if("undefined"==typeof mct.userConfig)throw Error("MCT.AudioHandler, broken user config dependency.");try{var a=mct.util.loadJSON("./lib/data/audio.json");this.meta=a.meta;"undefined"==typeof this.meta.channels&&(this.meta.channels={});this.meta.channels.amount=mct.userConfig.audio.channels.amount;this.meta.channels.status=[];this.effects=a.effects;this.effects.active=mct.userConfig.audio.effects.active;this.music=a.music;this.music.active=mct.userConfig.audio.music.active;
this.music.playOnStart=mct.userConfig.audio.music.playOnStart;this.players=[];this.playlists=a.playlists;this.playlists.positions={};for(var b in this.playlists.theme)this.playlists.positions[b]=-1}catch(c){console.log("Failed to load audio data, "+c)}};MCT.AudioHandler.prototype.constructor=MCT.AudioHandler;
MCT.AudioHandler.prototype.setPlayers=function(){for(var a=0;a<this.meta.channels.amount;a++)$("body").append('<audio class="audio" id="audio'+a+'" />'),this.players.push([$("#audio"+a),$("body").find($("#audio"+a))[0]]),this.meta.channels.status.push(0),this.players[a][0].attr("controls","controls"),this.players[a][0].hide()};
MCT.AudioHandler.prototype.setPlayerFadeEffects=function(a,b){if(!0==b){this.players[a][0].fadeTo(7500,0);var c=this;this.players[a][0].mouseover(function(){c.players[a][0].fadeTo("fast",1)});this.players[a][0].mouseout(function(){c.players[a][0].fadeTo("fast",0)})}else this.players[a][0].unbind("mouseover mouseout")};
MCT.AudioHandler.prototype.nextPlaylistTrack=function(a,b){if(1==this.music.active){if("number"!=typeof b||0!==b&&1!==b)nextChannel=0;else if(nextChannel=0==b?1:0,this.setPlayerFadeEffects(b,!1),clearInterval(mct.intervals["audioMusicChannel"+b]),"string"==typeof this.meta.channels.status[b])if("string"!=typeof a)a=this.meta.channels.status[b];else if(a!=this.meta.channels.status[b]){this.meta.channels.status[b]=a;this.checkPlaylistTrack(this,b,!0);return}this.players[nextChannel][0].show();"number"==
typeof b?this.players[nextChannel][0].css("opacity",0):(this.setPlayerFadeEffects(nextChannel,!0),1==this.music.playOnStart&&this.players[nextChannel][0].attr("autoplay","autoplay"));a="string"==typeof a?a:"default";this.meta.channels.status[nextChannel]=a;var c=this.playlists.positions[a];c<this.playlists.theme[a].length-1?c++:c=0;this.playlists.positions[a]=c;this.players[nextChannel][0].attr("src","data/audio/music/"+this.music[this.playlists.theme[a][c]]);"number"==typeof b&&(this.players[nextChannel][1].volume=
0,this.players[nextChannel][1].play());mct.intervals["audioMusicChannel"+nextChannel]=setInterval(this.checkPlaylistTrack.curry(this,nextChannel),1E3)}};
MCT.AudioHandler.prototype.checkPlaylistTrack=function(a,b,c){var d=a.players[b][1].currentTime>=a.players[b][1].duration-15;if(!0===c||d){a.nextPlaylistTrack(a.meta.channels.status[b],b);var f=0===b?1:0,k=1,l=!1;1==a.players[b][0].css("opacity")&&(l=!0);$(a.players[f][0]).animate({opacity:1},{duration:2500,progress:function(){150>=k&&(!0===l&&a.players[b][0].css("opacity",1-k/150),a.players[b][1].volume=1-k/150,a.players[f][1].volume=0+k/150,k++)},complete:function(){a.players[b][0].hide();a.setPlayerFadeEffects(f,
!0)}})}};
MCT.AudioHandler.prototype.playEffect=function(a,b,c){if(1==this.effects.active){c=1;do c++;while(0!==this.meta.channels.status[c]&&c<this.meta.channels.amount);if(c<this.meta.channels.amount)return!0===b&&this.players[c][0].attr("loop","loop"),this.players[c][0].attr("src","data/audio/effects/"+this.effects[a]),this.players[c][1].play(),this.meta.channels.status[c]=a,mct.intervals["audioEffectChannel"+c]=setInterval(this.releaseEffectChannel.curry(this,c),10),c;console.log("no free channels for "+a)}return-1};
MCT.AudioHandler.prototype.stopEffect=function(a){var b=1;do b++;while(this.meta.channels.status[b]!=a&&b<this.meta.channels.amount);this.meta.channels.status[b]==a&&(this.players[b][1].pause(),this.releaseEffectChannel(this,b))};MCT.AudioHandler.prototype.releaseEffectChannel=function(a,b){if(!0===a.players[b][1].ended||!0===a.players[b][1].paused)a.meta.channels.status[b]=0,clearInterval(mct.intervals["audioEffectChannel"+b]),1<b&&void 0!==a.players[b][0].attr("loop")&&a.players[b][0].removeAttr("loop")};
MCT.Pixi=function(){this.screen={width:1280,height:1024,ratio:0};this.stage=new PIXI.Stage(4342338,!0);this.renderer=PIXI.autoDetectRenderer(this.screen.width,this.screen.height,null,!0);this.autoResizeRenderer();this.setFpsCounter();this.windowTranslations=mct.util.loadJSON("./lib/data/display/txt/externals/window/lngs/"+mct.userConfig.language+".json");var a=this;$(window).resize(function(){a.autoResizeRenderer();mct.sceneHandler.update()})};MCT.Pixi.prototype.constructor=MCT.Pixi;
MCT.Pixi.prototype.autoResizeRenderer=function(){0!==this.screen.ratio?(this.screen.width=this.screen.baseSize.width,this.screen.height=this.screen.baseSize.height):this.screen.baseSize={width:this.screen.width,height:this.screen.height};this.screen.ratio=Math.min(window.innerWidth/this.screen.width,window.innerHeight/this.screen.height);this.screen.width*=this.screen.ratio;this.screen.height*=this.screen.ratio;this.renderer.resize(this.screen.width,this.screen.height);window.innerWidth>this.screen.width&&
$("body").css("padding-left",Math.floor((window.innerWidth-this.screen.width)/2)+"px")};MCT.Pixi.prototype.animate=function(a){-1<mct.userConfig.fps?global.setTimeout(function(){requestAnimFrame(a.animate.curry(a))},1E3/mct.userConfig.fps):requestAnimFrame(a.animate.curry(a));-1<a.fps[0]&&a.fps[0]++;TWEEN.update();a.renderer.render(a.stage)};
MCT.Pixi.prototype.setLoader=function(a){!0===a?(a=new PIXI.Text(this.windowTranslations["lt.windowLoading"],{font:Math.floor(40*this.screen.ratio)+"px Arial",fill:"FFFFFF"}),a.anchor={x:0.5,y:0.5},a.position.x=this.screen.width/2,a.position.y=this.screen.height/2,this.stage.addChild(a),this.loader=[!0,a]):!1===a&&(this.stage.removeChild(this.loader[1]),this.loader=[!1,{}])};
MCT.Pixi.prototype.loadAssets=function(a){this.setLoader(!0);loader=new PIXI.AssetLoader(["data/display/gfx/splitted/ti_stars.png","data/display/gfx/packed/gfx.atlas","data/display/gfx/packed/spinebird.atlas","data/display/gfx/packed/spinebird.json"]);var b=this;loader.onComplete=function(){a.call();b.setLoader(!1)};loader.load()};
MCT.Pixi.prototype.setFpsCounter=function(a,b){"undefined"==typeof a&&(b=this);"undefined"==typeof b.fps?(style={font:Math.floor(15*b.screen.ratio)+"px Arial",fill:"FFFFFF"},b.fps=[-1,new PIXI.Text("0",style)],b.fps[1].position.x=5*b.screen.ratio,b.fps[1].position.y=5*b.screen.ratio,b.fps[1].visible=!1):(!0===a&&0>b.fps[0]&&(b.fps[0]=0,b.fps[1].visible=!0,mct.intervals.fpsCounter=setInterval(b.setFpsCounter.curry(!1,b),1E3),a=!1,b.stage.addChild(b.fps[1])),b.fps[1].setText(0>b.fps[0]?0:b.fps[0]),
b.fps[0]=0,!0===a&&-1<b.fps[0]&&(clearInterval(mct.intervals.fpsCounter),b.fps[1].visible=!1,b.fps[0]=-1,b.stage.removeChild(b.fps[1])))};MCT.Survey=function(a){this.active=!1;this.type=a;this.lngTexts=mct.util.loadJSON("./lib/data/display/txt/externals/surveys/lngs/"+mct.userConfig.language+".json");this.data=mct.util.loadJSON("./lib/data/surveys.json");this.bindKey($("html"))};MCT.Survey.prototype.constructor=MCT.Survey;
MCT.Survey.prototype.bindKey=function(a){if("undefined"!=typeof this.data[this.type].hotkey){var b=this;a.keyup(function(a){a.which==b.data[b.type].hotkey&&b.toggle()})}};
MCT.Survey.prototype.toggle=function(){if(!0===this.active)$("#"+this.type+"Survey").remove(),$("#"+this.type+"SurveyTitle").remove(),this.active=!1;else{var a=Math.ceil(50*mct.pixi.screen.ratio),b=Math.ceil(mct.pixi.screen.width-100*mct.pixi.screen.ratio),c=Number($("body").css("padding-left").replace("px",""))+Math.ceil(50*mct.pixi.screen.ratio);$("body").append('<iframe id="'+this.type+'Survey" src="'+this.data[this.type].url+'" frameborder="0" style="border: 1px solid white; background-color: white; position: fixed; top: '+
a+"px; left: "+c+"px; width: "+b+"px; height: "+Math.ceil(mct.pixi.screen.height-100*mct.pixi.screen.ratio)+'px;"/>');$("body").append('<div id="'+this.type+'SurveyTitle" style="background-color: black; opacity: 0.7; position: fixed; top: '+(a+Math.ceil(1*mct.pixi.screen.ratio))+"px; left: "+(c+Math.ceil(mct.pixi.screen.ratio))+"px; width: "+b+"px; height: "+Math.ceil(50*mct.pixi.screen.ratio)+'px; color: white;"><h2 style="font-size: '+Math.ceil(25*mct.pixi.screen.ratio)+"px; margin: "+Math.ceil(12*
mct.pixi.screen.ratio)+"px "+Math.ceil(12*mct.pixi.screen.ratio)+'px">'+this.lngTexts["lt.survey."+this.type]+"</h2></div>");this.active=!0;var d=this;$("#"+this.type+"Survey").load(function(){d.bindKey($("#"+d.type+"Survey").contents().find("html").eq(0));var a=d.data[d.type].autofill,b=require("os");$("#"+d.type+"Survey").contents().find("#question"+a[0]).eq(0).find(".text").eq(0).val(b.type()+" "+b.release()+" "+b.arch()+" "+b.cpus()[0].model+" x"+b.cpus().length+" "+(!0===Boolean($("html").find("canvas")[0].getContext("webgl"))?
"WebGL":"Canvas"));mct.version.getVersionHash(function(b){$("#"+d.type+"Survey").contents().find("#question"+a[1]).eq(0).find(".text").eq(0).val(b)})})}};Function.prototype.curry=function(){if(1>arguments.length)return this;var a=this,b=Array.prototype.slice.call(arguments);return function(){return a.apply(this,b.concat(Array.prototype.slice.call(arguments)))}};$("html").keyup(function(a){27==a.which?mct.util.quit():112==a.which&&mct.pixi.setFpsCounter(!0,mct.pixi)});var mct=mct||{};
$(document).ready(function(){global.setTimeout(function(){mct.util=new MCT.Util;mct.version=new MCT.Version;mct.version.updateHashesFile();mct.userConfig=mct.util.loadJSON("./user/data/config.json");mct.intervals={};mct.pixi=new MCT.Pixi;mct.audioHandler=new MCT.AudioHandler;mct.sceneHandler=new MCT.DisplaySceneHandler;mct.game=new MCT.Game;mct.surveys=[new MCT.Survey("bugs"),new MCT.Survey("impressions"),new MCT.Survey("suggestions")];document.body.appendChild(mct.pixi.renderer.view);requestAnimFrame(mct.pixi.animate.curry(mct.pixi));
mct.pixi.loadAssets(function(){mct.game.start()})},1E-8)});
